is_debug: true
listen:
  type: port
  port: 8081
storage:
  host: saglyk-db
#  host: localhost
  port: 5432
  database: simple_db
  username: course_admin
  password: course_password
  pg_pool_max_conn: 100
app_version: 0.0.1
public_file_path: ./public
