version: '3.4'

services:
  db:
    image: postgres:14.1-alpine
    container_name: "saglyk-db"
    restart: always
    environment:
      - POSTGRES_USER=simple_admin
      - POSTGRES_PASSWORD=simple_password
      - POSTGRES_DB=simple_db
    ports:
      - '5434:5433'
    volumes:
      - /var/lib/postgresql/data
    networks:
      - network
  server:
      image: saglyk
      restart: unless-stopped
      container_name: "saglyk"
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8081:8081
      volumes:
        - ./public:/app/public
      depends_on:
        - db
      networks:
        - network


networks:
  network:
    driver: bridge

