version: '3.4'

services:
  db:
    image: postgres:14.1-alpine
    container_name: "db"
    restart: always
    environment:
      - POSTGRES_USER=simple_admin
      - POSTGRES_PASSWORD=simple_password
      - POSTGRES_DB=simple_db
    ports:
      - '5433:5432'
    volumes:
      - /var/lib/postgresql/data
    networks:
      - mynetwork
  server:
      image: app
      restart: unless-stopped
      container_name: "app"
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8081:8081
      volumes:
        - ./public:/app/public
      depends_on:
        - db
      networks:
        - mynetwork


networks:
  mynetwork:
    driver: bridge

