basePath: /v1
definitions:
  appresult.AppError:
    properties:
      code:
        type: string
      message:
        type: string
      status:
        type: boolean
    type: object
  appresult.AppSuccess:
    properties:
      code:
        type: string
      data: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  category.CategoryDTO:
    properties:
      Id:
        type: integer
      count:
        type: integer
      createdAt:
        type: string
      image:
        type: string
      name:
        type: string
    type: object
  category.CategoryIdDTO:
    properties:
      Id:
        type: integer
      image:
        type: string
      name:
        type: string
    type: object
  category.DataDTO:
    properties:
      count:
        type: integer
      subCat:
        items:
          $ref: '#/definitions/category.SubCategoryDTO'
        type: array
    type: object
  category.ReqIdDTO:
    properties:
      Id:
        type: integer
    type: object
  category.SubCategoryDTO:
    properties:
      Id:
        type: integer
      catName:
        type: string
      createdAt:
        type: string
      imagePath:
        type: string
      item: {}
      name:
        type: string
    type: object
  category.SubCategoryIdDTO:
    properties:
      Id:
        type: integer
      catId:
        type: integer
      image:
        type: string
      item: {}
      name:
        type: string
    type: object
host: 216.250.12.77
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Testing Swagger APIs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Admin Course APIs
  version: "1.0"
paths:
  /categories/add:
    post:
      consumes:
      - application/json
      description: create and update data  categories
      parameters:
      - description: Create JSON
        in: body
        name: categories
        required: true
        schema:
          $ref: '#/definitions/category.CategoryIdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      tags:
      - categories
  /categories/add-product:
    post:
      consumes:
      - application/json
      description: create and update data  product
      parameters:
      - description: Create JSON
        in: body
        name: categories
        required: true
        schema:
          $ref: '#/definitions/category.SubCategoryIdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      tags:
      - categories
  /categories/delete:
    post:
      consumes:
      - application/json
      description: delete data  banner
      parameters:
      - description: Delete JSON
        in: body
        name: categories
        required: true
        schema:
          $ref: '#/definitions/category.ReqIdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      tags:
      - categories
  /categories/delete-product:
    post:
      consumes:
      - application/json
      description: delete data  product
      parameters:
      - description: Delete JSON
        in: body
        name: categories
        required: true
        schema:
          $ref: '#/definitions/category.ReqIdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      tags:
      - categories
  /categories/file:
    post:
      consumes:
      - multipart/form-data
      description: file upload
      parameters:
      - description: this is a test file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      tags:
      - file
  /categories/get:
    post:
      consumes:
      - application/json
      description: one data category
      parameters:
      - description: Get One JSON
        in: body
        name: categories
        required: true
        schema:
          $ref: '#/definitions/category.ReqIdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/category.DataDTO'
      security:
      - BearerAuth: []
      tags:
      - categories
  /categories/get-all:
    get:
      consumes:
      - application/json
      description: all data categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/category.CategoryDTO'
            type: array
      security:
      - BearerAuth: []
      tags:
      - categories
  /categories/get-product:
    post:
      consumes:
      - application/json
      description: product data
      parameters:
      - description: Get One JSON
        in: body
        name: categories
        required: true
        schema:
          $ref: '#/definitions/category.ReqIdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/category.SubCategoryDTO'
      security:
      - BearerAuth: []
      tags:
      - categories
swagger: "2.0"
