name: pipeline
on:
  push:
    branches:
      - "dev"
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: print out example job
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            echo "Nice Job!!!"
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#      - name: executing remote ssh commands using password
#        uses: appleboy/ssh-action@v0.1.10
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          key: ${{ secrets.SSH_KEY }}
#          port: 22
#          script: |
#            whoami
#
#  deploy:
#    name: build && push image to docker hub
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          ref: dev
#
#      - name: setup docker buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: docker login
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: build and push api
#        id: build-push-api
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: Dockerfile
#          push: true
#          tags: guvandyk/eat-healthy-food:latest
#
#      - name: main (merge)
#        if: github.event_name != 'pull_request'
#        shell: bash
#        run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
#
#      - name: main (pull request)
#        if: github.event_name == 'pull_request'
#        shell: bash
#        run: echo "BRANCH=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
