name: pipeline
on:
  push:
    branches:
      - "dev"
      - "main"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           ref: dev
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run:  | 
              ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          key: ${{ secrets.SSH_KEY }}
#          port: 22
#          script: |
#            whoami
#  deploy:
#    name: build && push image to docker hub
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          ref: dev
#
#      - name: setup docker buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: docker login
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: build and push api
#        id: build-push-api
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: Dockerfile
#          push: true
#          tags: guvandyk/eat-healthy-food:latest

#      - name: main (merge)
#        if: github.event_name != 'pull_request'
#        shell: bash
#        run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
#
#      - name: main (pull request)
#        if: github.event_name == 'pull_request'
#        shell: bash
#        run: echo "BRANCH=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
